### ISSUE TITLE
Wrong card number format for American Express

### ISSUE THREAD

**Issue by impomezia** [JohnyDays/react-credit-card#12]
American Express uses different format for card number, for example: **3714 496353 98431**. There is ok https://jessepollak.github.io/card/ some test numbers: http://www.paypalobjects.com/en_US/vhelp/paypalmanager_help/credit_card_numbers.htm

**Comment by stevewillard** [comment]
This should be fixed by #5

**Comment by JohnyDays** [comment]
As @stevewillard said, fixed by #5, cheers 👍
