### ISSUE TITLE
Card back is shown instead of card front in Safari

### ISSUE THREAD

**Issue by shatran** [JohnyDays/react-credit-card#3]
On Safari v8.0.6 when card is in its initial state (not flipped), the card back is shown instead of the front. when flipping the card, the card becomes invisible with just a shadow surrounding it.
I've attached some screenshots:
initial state:
![screen shot 2015-06-10 at 12 48 28 pm](https://cloud.githubusercontent.com/assets/6247855/8079748/62816966-0f6f-11e5-9069-07bba1528037.png)
flipped state:
![screen shot 2015-06-10 at 12 52 09 pm](https://cloud.githubusercontent.com/assets/6247855/8079752/6a971682-0f6f-11e5-90ea-9b2d5653bf46.png)

**Comment by JohnyDays** [comment]
Closing it since you fixed it in #4. Thanks :+1:
