### ISSUE TITLE
License

### ISSUE THREAD

**Issue by clamp** [JohnyDays/react-credit-card#6]
Hi,

I'd love to use this and translate it into es6 React, but you don't seem to have a license. Can you add an MIT license if your intent was to let people use this?

Sorry to bother!

Matt

**Comment by JohnyDays** [comment]
Of course, here you go! 
I'm not used to legal jabber yet, feel free to use it. If you do translate it into ES6, i'd love a pull request. I've only been using ES6 recently as well.

Cheers :beer:
