### ISSUE TITLE
Produces warnin in webpack

### ISSUE THREAD

**Issue by Elliot128** [JohnyDays/react-credit-card#7]
This produces a warning in webpack because it is a pre-built javascript file:

WARNING in ./~/react-credit-card/~/payment/lib/payment.js
Critical dependencies:
1:459-466 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/react-credit-card/~/payment/lib/payment.js 1:459-466

Is there anyway to provide the source in npm?

**Comment by JohnyDays** [comment]
Hey @elliotatRetireup,the source is actually provided in npm. 

It is unfortunately coffeescript, a decision I would not have taken recently with the widespread usage(including mine) of babel. 

If that is not a problem for you, just require node_modules/react-credit-card/source/card.cjsx. Regardless, the built script is just a simple translation, it shouldn't cause you problems(not sure why webpack is warning).

**Comment by sstern6** [comment]
@JohnyDays I was getting the same issue when requiring 'react-credit-card' in my JSX file, but then when I required what you advised ^^^^, the render function in React cant compile the coffee script.  Any more suggestions?

Thank you

**Comment by jgarcia99** [comment]
Yea I still get the same problem

**Comment by JohnyDays** [comment]
You need to compile it using cjsx https://github.com/jsdf/coffee-react-transform not coffee-script, since it's a mix of coffee and jsx. There's also a webpack loader for it https://github.com/KyleAMathews/cjsx-loader
